---
title: "Heteroplasmy_bellenguez_MR"
output: html_notebook
---

## Libraries

Loads the appropriate packages for MR analysis

``` {r eval=FALSE}
library(tidyverse) # Data wrangling 

library(cowplot)

library(ggman)

library(TwoSampleMR) # MR 

library(RadialMR) # Radial MR sensitivity analysis 

library(phenoscanner)

library(LDlinkR) # LD and proxy snps

library(janitor)

library(MVMR)         # Multivarble MR

library(RMVMR)

library(MendelianRandomization)

library(MVMRmode)

#MVMR Munge proxies
source("/wynton/group/andrews/users/achatterjee/mtdnacn/Brian-Estimating-Causality-mtDNAcn-on-Alzheimer/Scripts/Functions/mvmr_munge_proxies.R")

#Munge proxies
source("/wynton/group/andrews/users/achatterjee/mtdnacn/Brian-Estimating-Causality-mtDNAcn-on-Alzheimer/Scripts/Functions/munge_proxies.R")

# Define column types for summary statistics (MDNA and AD GWAS)
coltypes = cols(
  ID = col_character(),
  CHROM = col_double(),
  POS = col_double(),
  REF = col_character(),
  ALT = col_character(),
  AF = col_double(),
  TRAIT = col_character(),
  BETA = col_double(),
  SE = col_double(),
  Z = col_double(),
  P = col_double(),
  N = col_double(),
  OR = col_double(),
  OR_L95 = col_double(),
  OR_U95 = col_double(),
  DIR = col_character(),
  G1000_ID = col_character(),
  G1000_VARIANT = col_character(),
  DBSNP_ID = col_character(),
  DBSNP_VARIANT = col_character(),
  OLD_ID = col_character(),
  OLD_VARIANT = col_character()
)

```

#Read in formatted heteroplasmy
```{r}
heteroplasmy <- read_tsv("/wynton/group/andrews/data/summary_stats/results/Nandakumar2021heteroplasmy") #Already formatted and these are the GWS SNPs
```

#Read in Bellenguez AD
```{r}
outcome_path_bellenguez = "/wynton/group/andrews/data/summary_stats/results/Bellenguez2022load.chrall.CPRA_b37.tsv.gz"

# Import Code for outcome GWAS 
OutcomeAD_Bellenguez <- read_tsv(outcome_path_bellenguez,comment="#")

# Rename right-side variables to match column names of your GWAS dataset 
outcome_AD_Format_Bellenguez <- OutcomeAD_Bellenguez %>%
  format_data(.,
    type = "outcome",
    snps = NULL,
    header = TRUE,
    phenotype_col = "Phenotype",
    snp_col = "DBSNP_ID",
    beta_col = "BETA",
    se_col = "SE",
    eaf_col = "AF",
    effect_allele_col = "ALT",
    other_allele_col = "REF",
    pval_col = "P",
    samplesize_col = "N",
    z_col = "Z",
    chr_col = "CHROM",
    pos_col = "POS",
    log_pval = FALSE
) %>%
  as_tibble()

outcome_AD_Format_Bellenguez <- outcome_AD_Format_Bellenguez %>%
mutate(outcome = "bellenguez")
```

#LD proxy SNPs
```{r}
# extract exposure SNPs present in outcome (keeps all the columns from the left data frame and omits the corresponding rows from the right data frame)
outcome_clump <- semi_join(
  outcome_AD_Format_Bellenguez, heteroplasmy, by = "SNP"
)
# Exposure SNPs not present in outomce
exp_snps_wo <- anti_join(
  heteroplasmy, outcome_AD_Format_Bellenguez, by = "SNP" 
) #3 SNPs


# Use LDLinkR to identify proxy snps
LDproxy_batch(exp_snps_wo$SNP, 
        pop = "CEU", 
        r2d = "r2", 
        token = 'a6deee62cc4a', 
        append = TRUE,
        genome_build = "grch37")
system("mv combined_query_snp_list_grch37.txt heteroplasmy_bellenguez_proxy_snps.txt")

# Munge proxy snp file
outcome_dat <- munge_proxies("/wynton/group/andrews/users/achatterjee/mtdnacn/Brian-Estimating-Causality-mtDNAcn-on-Alzheimer/data/proxy_snps/heteroplasmy_bellenguez_proxy_snps.txt", outcome_AD_Format_Bellenguez, outcome_clump)
```
#Harmonize
```{r}
harmonised_data <- harmonise_data(heteroplasmy, outcome_dat, action = 2) %>% as_tibble() %>%
#  mutate(
#    apoe_region = case_when(
#      chr.outcome == 19 & between(pos.outcome, 44912079, 45912079) ~ TRUE,
#      TRUE ~ FALSE
#    ), 
#    gws.outcome = ifelse(pval.outcome < 5e-8, TRUE, FALSE), 
#   mr_keep = ifelse(mr_keep == FALSE | apoe_region == TRUE | gws.outcome == TRUE, FALSE, TRUE)
#  )
  filter(pval.exposure < 5e-8)
```

#Export harmonized data
```{r}
#write_csv(harmonised_data, "/wynton/group/andrews/users/achatterjee/mtdnacn/Brian-Estimating-Causality-mtDNAcn-on-Alzheimer/data/Harmonized_Datasets/harmonized_heteroplasmy_bellenguez.csv")
```

#MR
```{r}
mr <- mr(harmonised_data)
```

#F statistic (not working because don't have eaf?)
```{r}
f_stat = function(N, K, R){
  f = ((N-K-1) / K) * (R/(1-R))
  f
}

## Proportion of phenotypic variance explained by SNP
## https://doi.org/10.1371/journal.pone.0120758.s001

snp.pve <- function(eaf, beta, se, n){
  (2*eaf*(1 - eaf)*beta^2) / (2 * beta * eaf * (1-eaf) + se^2 * 2 * n * eaf * (1-eaf))
}

f_res <- harmonised_data %>%
  group_by(exposure, outcome) %>%
  filter(mr_keep == TRUE) %>%
  mutate(
    samplesize.exposure = 982072,
    pve = snp.pve(eaf.exposure, beta.exposure, se.exposure, samplesize.exposure),
    f = f_stat(samplesize.exposure, 1, pve),
    # f = abs(beta.exposure)^2 / se.exposure^2
  ) %>%
  dplyr::select(SNP, exposure, outcome, effect_allele.exposure, eaf.exposure, beta.exposure, se.exposure, samplesize.exposure) %>% 
  dplyr::summarise(
    pve = sum(pve, na.rm = T),
    k = n(),
    samplesize = max(samplesize.exposure),
    f = mean(f, na.rm = T),
  )
f_res
```

##Sensitivity analyses
```{r}
mr_heterogeneity(harmonised_data)
mr_pleiotropy_test(harmonised_data)
```

##Radial MR
```{r}
radial_dat <- harmonised_data %>% filter(mr_keep == T) %>% dat_to_RadialMR()
radial_res <- ivw_radial(radial_dat$heteroplasmy.bellenguez, alpha = 0.05/nrow(radial_dat$heteroplasmy.bellenguez)) #no significant outliers
```
