---
title: "R Notebook"
output: html_notebook
---

## Libraries

Loads the appropriate packages for MR analysis

``` {r eval=FALSE}
library(tidyverse) # Data wrangling 

library(cowplot)

library(ggman)

library(TwoSampleMR) # MR 

library(RadialMR) # Radial MR sensitivity analysis 

library(phenoscanner)

library(LDlinkR) # LD and proxy snps

library(janitor)

library(MVMR)         # Multivarble MR

library(RMVMR)

library(MendelianRandomization)

library(MVMRmode)

#MVMR Munge proxies
source("/wynton/group/andrews/users/achatterjee/mtdnacn/Brian-Estimating-Causality-mtDNAcn-on-Alzheimer/Scripts/Functions/mvmr_munge_proxies.R")

#Munge proxies
source("/wynton/group/andrews/users/achatterjee/mtdnacn/Brian-Estimating-Causality-mtDNAcn-on-Alzheimer/Scripts/Functions/munge_proxies.R")

# Define column types for summary statistics (MDNA and AD GWAS)
coltypes = cols(
  ID = col_character(),
  CHROM = col_double(),
  POS = col_double(),
  REF = col_character(),
  ALT = col_character(),
  AF = col_double(),
  TRAIT = col_character(),
  BETA = col_double(),
  SE = col_double(),
  Z = col_double(),
  P = col_double(),
  N = col_double(),
  OR = col_double(),
  OR_L95 = col_double(),
  OR_U95 = col_double(),
  DIR = col_character(),
  G1000_ID = col_character(),
  G1000_VARIANT = col_character(),
  DBSNP_ID = col_character(),
  DBSNP_VARIANT = col_character(),
  OLD_ID = col_character(),
  OLD_VARIANT = col_character()
)

`%nin%` = negate(`%in%`)

```

#Read in formatted heteroplasmy
```{r}
heteroplasmy <- read_tsv("/wynton/group/andrews/data/summary_stats/results/Nandakumar2021heteroplasmy") #Already formatted and these are the GWS SNPs
```

## Outcome: Nalls PD
```{r}
outcome_path_nalls = "/wynton/group/andrews/data/summary_stats/resources/gwas/Nalls2019/nallsEtAl2019_allSamples_allVariants.tab"

# Import Code for outcome GWAS 
OutcomeAD_Nalls <- read_tsv(outcome_path_nalls,comment="#")

#Format using MungeSumStats
OutcomeAD_Nalls_munge_sumstats <- OutcomeAD_Nalls %>%
  #rename_with(~ "SNP", .cols = variant_id) %>%
  #filter(nchar(effect_allele) == 1 & nchar(other_allele) == 1) %>% 
  MungeSumstats::format_sumstats(
    ., 
    ref_genome = "GRCh37", 
    # convert_ref_genome = "GRCh37", 
    #dbSNP = 144, 
    return_data = TRUE
) %>%
  as_tibble() %>%
  filter(CHR %nin% c("X", "Y")) %>%
  mutate(CHR = as.numeric(as.character(CHR)))


#Read munged sumstats in instead
OutcomeAD_Nalls_munge_sumstats <- read_tsv("/wynton/group/andrews/data/summary_stats/results/Nalls2019_PD.tsv")

#Make N column N_CAS+N_CON
OutcomeAD_Nalls_munge_sumstats <- OutcomeAD_Nalls_munge_sumstats %>%
  mutate(N = N_CAS + N_CON)


# Rename right-side variables to match column names of your GWAS dataset 
outcome_AD_Format_Nalls <- OutcomeAD_Nalls_munge_sumstats %>%
  format_data(.,
    type = "outcome",
    #snps = NULL,
    header = TRUE,
    snp_col = "SNP",
    beta_col = "BETA",
    se_col = "SE",
    eaf_col = "FRQ",
    effect_allele_col = "A1",
    other_allele_col = "A2",
    pval_col = "P",
    samplesize_col = "N",
    pos_col = "BP",
    chr_col = "CHR",
    log_pval = FALSE
) %>%
  as_tibble()

outcome_AD_Format_Nalls <- outcome_AD_Format_Nalls %>%
mutate(outcome = "nalls_PD")
```
#LD proxy SNPs
```{r}
# extract exposure SNPs present in outcome (keeps all the columns from the left data frame and omits the corresponding rows from the right data frame)
outcome_clump <- semi_join(
  outcome_AD_Format_Nalls, heteroplasmy, by = "SNP"
)
# Exposure SNPs not present in outomce
exp_snps_wo <- anti_join(
  heteroplasmy, outcome_AD_Format_Nalls, by = "SNP" 
) #26 SNPs


# Use LDLinkR to identify proxy snps
LDproxy_batch(exp_snps_wo$SNP, 
        pop = "CEU", 
        r2d = "r2", 
        token = 'a6deee62cc4a', 
        append = TRUE,
        genome_build = "grch37")
system("mv combined_query_snp_list_grch37.txt heteroplasmy_nalls_proxy_snps_Aadrita.txt")

# Munge proxy snp file
outcome_dat <- munge_proxies("/wynton/group/andrews/users/achatterjee/mtdnacn/Brian-Estimating-Causality-mtDNAcn-on-Alzheimer/data/proxy_snps/heteroplasmy_nalls_proxy_snps_Aadrita.txt", outcome_AD_Format_Nalls, outcome_clump)
```

#Harmonise
```{r}
harmonised_data <- harmonise_data(heteroplasmy, outcome_dat, action = 2) %>% as_tibble() %>%
#  mutate(
#    apoe_region = case_when(
#      chr.outcome == 19 & between(pos.outcome, 44912079, 45912079) ~ TRUE,
#      TRUE ~ FALSE
#    ), 
#    gws.outcome = ifelse(pval.outcome < 5e-8, TRUE, FALSE), 
#   mr_keep = ifelse(mr_keep == FALSE | apoe_region == TRUE | gws.outcome == TRUE, FALSE, TRUE)
#  )
  filter(pval.exposure < 5e-8)
```

#Export
```{r}
write_csv(harmonised_data, "/wynton/group/andrews/users/achatterjee/mtdnacn/Brian-Estimating-Causality-mtDNAcn-on-Alzheimer/data/Harmonized_Datasets/heteroplasmy_nandakumar_nalls_univariate_harmonised_data.csv")
```

#Import harmonised dataset
```{r}
harmonised_data <- read_csv("/wynton/group/andrews/users/achatterjee/mtdnacn/Brian-Estimating-Causality-mtDNAcn-on-Alzheimer/data/Harmonized_Datasets/heteroplasmy_nandakumar_nalls_univariate_harmonised_data.csv")
```

#MR
```{r}
mr_res <- mr(harmonised_data, method_list = c(
  "mr_two_sample_ml",  "mr_egger_regression", "mr_weighted_median", 
  "mr_ivw_fe", "mr_ivw_mre",
  "mr_simple_mode", "mr_weighted_mode"
  ))

res_single <- mr_singlesnp(harmonised_data, all_method = c("mr_ivw_fe", "mr_egger_regression", "mr_weighted_median", "mr_weighted_mode")) %>% as_tibble()
```

##Sensitivity analyses
```{r}
mr_heterogeneity(harmonised_data)
mr_pleiotropy_test(harmonised_data)
```

##Radial MR (no outliers detected)
```{r}
radial_dat <- harmonised_data %>% filter(mr_keep == T) %>% dat_to_RadialMR()
radial_res <- ivw_radial(radial_dat$heteroplasmy.nalls_PD, alpha = 0.05/nrow(radial_dat$heteroplasmy.nalls_PD)) #no significant outliers
```

#MRLap (didn't do this)
```{r}
#remotes::install_github("n-mounier/MRlap")
library(MRlap)

#Reformatting exposure
reformat_mtDNAcn_longchamps <- mtDNAcn_longchamps %>% 
  rename(rsid = "DBSNP_ID", chr = "CHROM", ) %>% 
  select(-OR)

#Reformatting outcome (use total sample size instead of effective)
outcome <- OutcomeAD_Nalls %>% 
  dplyr::rename(rs = DBSNP_ID, chr = CHROM) %>% 
  select(-OR) %>% 
  filter(rs != 'rs429358')

mrlap <- MRlap(exposure = reformat_mtDNAcn_longchamps,
               exposure_name = "exposure",
               outcome = outcome,
               outcome_name = "outcome",
               MR_pruning_dist = 10000,
               MR_pruning_LD = 0.001,
               ld = "/wynton/group/andrews/data/eur_w_ld_chr/",
               hm3 = "/wynton/group/andrews/data/w_hm3.snplist")
mrlap

mrlap$MRcorrection$IVs

filter(outcome, rs %in% mrlap$MRcorrection$IVs)

```