---
title: "R Notebook"
output: html_notebook
---

## Libraries

Loads the appropriate packages for MR analysis

``` {r eval=FALSE}
library(tidyverse) # Data wrangling 

library(cowplot)

library(ggman)

library(TwoSampleMR) # MR 

library(RadialMR) # Radial MR sensitivity analysis 

library(phenoscanner)

library(LDlinkR) # LD and proxy snps

library(janitor)

library(MVMR)         # Multivarble MR

library(RMVMR)

library(MendelianRandomization)

library(MVMRmode)

#MVMR Munge proxies
source("/wynton/group/andrews/users/achatterjee/mtdnacn/Brian-Estimating-Causality-mtDNAcn-on-Alzheimer/Scripts/Functions/mvmr_munge_proxies.R")

#Munge proxies
source("/wynton/group/andrews/users/achatterjee/mtdnacn/Brian-Estimating-Causality-mtDNAcn-on-Alzheimer/Scripts/Functions/munge_proxies.R")

# Define column types for summary statistics (MDNA and AD GWAS)
coltypes = cols(
  ID = col_character(),
  CHROM = col_double(),
  POS = col_double(),
  REF = col_character(),
  ALT = col_character(),
  AF = col_double(),
  TRAIT = col_character(),
  BETA = col_double(),
  SE = col_double(),
  Z = col_double(),
  P = col_double(),
  N = col_double(),
  OR = col_double(),
  OR_L95 = col_double(),
  OR_U95 = col_double(),
  DIR = col_character(),
  G1000_ID = col_character(),
  G1000_VARIANT = col_character(),
  DBSNP_ID = col_character(),
  DBSNP_VARIANT = col_character(),
  OLD_ID = col_character(),
  OLD_VARIANT = col_character()
)

`%nin%` = negate(`%in%`)
```


## Exposure 1: Longchamps
``` {r read_in_longchamps}

exposure_path_longchamps = "/wynton/group/andrews/data/summary_stats/results/Longchamps2021mtdnacn.chrall.CPRA_b37.tsv.gz"

mtDNAcn_longchamps <- read_tsv(exposure_path_longchamps,comment="#")


#Genome wide signficant SNPs
mtDNAcn_longchamps_gws <- filter(mtDNAcn_longchamps, P < 5e-8)


#Clump locally
mtDNAcn_clump_longchamps <- mtDNAcn_longchamps_gws %>% 
  filter(P < 1e-5) %>%
  select(rsid = DBSNP_ID, pval = P) %>%
  ieugwasr::ld_clump(
    dat = .,
    clump_kb = 10000,
    clump_r2 = 0.001,
    clump_p = 0.99,
    bfile = '/wynton/group/andrews/data/reference_panels/EUR_All_Chr',
    plink_bin = '/wynton/home/andrews/achatterjee/plink'
  )


#Remove APOE region
mtDNAcn_clump_longchamps <- filter(mtDNAcn_longchamps_gws, !(CHROM == 19 & between(POS, 44912079, 45912079)))

#Select columns necessary for PRS using PLINK
mtDNAcn_clump_longchamps_filtered <- mtDNAcn_clump_longchamps %>% 
  select(DBSNP_ID, REF, BETA,) %>% 
  dplyr::rename(SNP = DBSNP_ID) %>% 
  filter(!is.na(SNP))


#Export
write.table(mtDNAcn_clump_longchamps_filtered, file = "/wynton/group/andrews/users/achatterjee/prs/data/mtDNAcn_clump_longchamps_apoe_removed.txt", sep = "\t", row.names = FALSE, col.names = TRUE, quote = FALSE)
```


## Exposure 1: Hagg
``` {r read_in_hagg}

exposure_path_hagg = "/wynton/group/andrews/data/summary_stats/results/Hagg2020mtdnacn.chrall.CPRA_b37.tsv.gz"

mtDNAcn_hagg <- read_tsv(exposure_path_hagg,comment="#")

#Clump locally
mtDNAcn_clump_hagg <- mtDNAcn_hagg %>% 
  filter(P < 1e-5) %>%
  select(rsid = DBSNP_ID, pval = P) %>%
  ieugwasr::ld_clump(
    dat = .,
    clump_kb = 10000,
    clump_r2 = 0.001,
    clump_p = 0.99,
    bfile = '/wynton/group/andrews/data/reference_panels/EUR_All_Chr',
    plink_bin = '/wynton/home/andrews/achatterjee/plink'
  )

#Append the SNPS to Format_mtDNAcn_hagg so we can get all the columns and get gws 
mtDNAcn_hagg_gws <- filter(mtDNAcn_hagg, DBSNP_ID %in% mtDNAcn_clump_hagg$rsid, P < 5e-8)

#Remove APOE region
mtDNAcn_clump_hagg <- filter(mtDNAcn_hagg_gws, !(CHROM == 19 & between(POS, 44912079, 45912079)))

#Select columns necessary for PRS using PLINK
mtDNAcn_clump_hagg_filtered <- mtDNAcn_clump_hagg %>% 
  select(DBSNP_ID, REF, BETA,) %>% 
  dplyr::rename(SNP = DBSNP_ID) %>% 
  filter(!is.na(SNP))

#Export
write.table(mtDNAcn_clump_hagg_filtered, file = "/wynton/group/andrews/users/achatterjee/prs/data/mtDNAcn_clump_hagg_apoe_removed.txt", sep = "\t", row.names = FALSE, col.names = TRUE, quote = FALSE)
```

## Exposure 1: Chong
``` {r read_in_chong}

exposure_path_chong = "/wynton/group/andrews/data/summary_stats/results/Chong2022mtdnacn_eur.chrall.CPRA_b37.tsv"

mtDNAcn_chong <- read_tsv(exposure_path_chong,comment="#")


#Clump locally
mtDNAcn_clump_chong <- mtDNAcn_chong %>% 
  filter(P < 1e-5) %>%
  select(rsid = DBSNP_ID, pval = P) %>%
  ieugwasr::ld_clump(
    dat = .,
    clump_kb = 10000,
    clump_r2 = 0.001,
    clump_p = 0.99,
    bfile = '/wynton/group/andrews/data/reference_panels/EUR_All_Chr',
    plink_bin = '/wynton/home/andrews/achatterjee/plink'
  )

#Append the SNPS to Format_mtDNAcn_chong so we can get all the columns and get gws 
mtDNAcn_chong_gws <- filter(mtDNAcn_chong, DBSNP_ID %in% mtDNAcn_clump_chong$rsid, P < 5e-8)

#Remove APOE region
mtDNAcn_clump_chong <- filter(mtDNAcn_chong_gws, !(CHROM == 19 & between(POS, 44912079, 45912079)))

#Select columns necessary for PRS using PLINK
mtDNAcn_clump_chong_filtered <- mtDNAcn_clump_chong %>% 
  select(DBSNP_ID, REF, BETA,) %>% 
  dplyr::rename(SNP = DBSNP_ID) %>% 
  filter(!is.na(SNP))

#Export
write.table(mtDNAcn_clump_chong_filtered, file = "/wynton/group/andrews/users/achatterjee/prs/data/mtDNAcn_clump_chong_apoe_removed.txt", sep = "\t", row.names = FALSE, col.names = TRUE, quote = FALSE)
```

