---
title: "R Notebook"
output: html_notebook
editor_options: 
  chunk_output_type: console
---

#Libraries


#Read in dataframe
```{r}
prs_results <- read_csv("/wynton/group/andrews/users/achatterjee/mtdnacn/Brian-Estimating-Causality-mtDNAcn-on-Alzheimer/prs/data/prs_results_mtdnacn_onto_AD.csv")

prs_results$Exposure <- as.character(prs_results$Exposure)
prs_results$Exposure <- factor(prs_results$Exposure, levels = sort(unique(prs_results$Exposure)))
```

#Plot
```{r}
prs_plot <- ggplot(prs_results, aes(
  x = Exposure, 
  y = OR,
  ymin = CI_lower,
  ymax = CI_upper
)) +
  geom_pointrange(aes(color = `Pr(>|z|)` < 0.05)) +
  geom_hline(yintercept = 1, linetype = "dashed", color = "gray40") +  # Add dashed line at OR = 1
  #geom_pointrange(color = "steelblue") +
  #geom_errorbar(width = 0.3, color = "steelblue") +
  coord_flip() +
  labs(
    title = "PRS Analysis of mtDNAcn and AD",                  # Title
    x = "Exposure",
    y = "Odds Ratio (95% CI)"
  ) +
  theme_bw() +
  theme(
    plot.title = element_text(hjust = 0.5),  # Centered title
    text = element_text(size = 12), 
    axis.ticks = element_blank(),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank()) +
  scale_color_manual(values = c("TRUE" = "red", "FALSE" = "black")) +
  theme(legend.position = "none") +
  theme(aspect.ratio = 3/5)

prs_plot

#Save plot
#ggsave("/wynton/group/andrews/users/achatterjee/prs/plots/prs_plot_mtdnacn_onto_ad.png", prs_plot, width = 4.5, height = 4, dpi = 600)

```

