---
title: "R Notebook"
output: html_notebook
editor_options: 
  chunk_output_type: console
---

#Load packages
```{r}
library(dplyr)
library(readr)
library(broom)
library(ggplot2)
library(tidyr)
library(tidyverse)
```

#FORWARD DIRECTION
##Load dataset
```{r}
lhc_mr_results <- read_csv("/wynton/group/andrews/users/achatterjee/mtdnacn/Brian-Estimating-Causality-mtDNAcn-on-Alzheimer/results/Aadrita_results/LHC-MR_forward_direction_all_results.csv")
```

##Make OR
```{r}
odds_ratios <- lhc_mr_results %>%
  mutate(
    OR = exp(beta),
    OR_lci95 = exp(beta - 1.96 * SE),
    OR_uci95 = exp(beta + 1.96 * SE),
    pval = `P-Value`
  ) %>%
  mutate(
    Outcome = recode(Outcome,
                     "Bellenguez" = "AD/dementia",
                     "Kunkle" = "AD",
                     "Nalls" = "PD")
  ) %>%
  mutate(
    pval_fdr = p.adjust(pval, method = "fdr")
  )

```

##Plot 
```{r}
or_plot <- ggplot(odds_ratios, aes(y = Exposure, x = OR, xmin = OR_lci95, xmax = OR_uci95)) +
  geom_pointrange(aes(color = pval_fdr < 0.05)) +
  facet_wrap(~Outcome, scales = "free_x") +
  geom_vline(xintercept = 1, linetype = 2) +
  scale_x_continuous(
  labels = function(x) gsub("\\.?0+$", "", format(x, digits = 2)),
  expand = expansion(mult = c(0.15, 0.15))
) +
  labs(
    title = "LHC-MR Results for mtDNAcn onto AD\nand PD",
    x = "Odds Ratio (95% CI)", y = "Exposure"
  ) +
  theme_bw() +
  theme(
    text = element_text(size = 12),
    axis.ticks = element_blank(),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    plot.title = element_text(hjust = 0.5),
    strip.text = element_text(face = "bold"),
    strip.background = element_blank(),
    legend.position = "none"
  ) +
  scale_color_manual(values = c("TRUE" = "red", "FALSE" = "black"))

or_plot


#ggsave("/wynton/group/andrews/users/achatterjee/mtdnacn/Brian-Estimating-Causality-mtDNAcn-on-Alzheimer/results/Aadrita_results/plots/OR_lhc-mr_forward_dir.png", or_plot, units = "in", width = 6, height = 4, dpi = 300) 
```

#REVERSE DIRECTION
##Load dataset
```{r}
lhc_mr_results <- read_csv("/wynton/group/andrews/users/achatterjee/mtdnacn/Brian-Estimating-Causality-mtDNAcn-on-Alzheimer/results/Aadrita_results/LHC-MR_reverse_direction_all_results.csv")
```

##Make CI (not using OR in reverse direction) and change exposure names
```{r}
lhc_mr_results_clean <- lhc_mr_results %>%
  mutate(
    CI_lci95 = beta - 1.96 * SE,
    CI_uci95 = beta + 1.96 * SE,
    pval = `P-Value`
  )

lhc_mr_results_new_names <- lhc_mr_results_clean %>%
  mutate(Exposure = case_when(
    Exposure == "Kunkle" ~ "AD",
    Exposure == "Bellenguez" ~ "AD/dementia",
    Exposure == "Nalls" ~ "PD",
    TRUE ~ Exposure  # keep other names unchanged
  ))
```

##Plot 
```{r}
or_plot <- ggplot(lhc_mr_results_new_names, aes(y = Exposure, x = beta, xmin = CI_lci95, xmax = CI_uci95)) +
  geom_pointrange(aes(color = pval < 0.05)) +
  facet_wrap(~Outcome) +
  geom_vline(xintercept = 0, linetype = 2) +
  labs(title = "LHC-MR Results for AD and PD\nonto mtDNAcn", x = "Odds Ratio (95% CI)", y = "Exposure") +
  theme_bw() +
  theme(
    text = element_text(size = 12),
    axis.ticks = element_blank(),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    plot.title = element_text(hjust = 0.5),
    strip.text = element_text(face = "bold"),
    strip.background = element_blank()
  ) +
  scale_color_manual(values = c("TRUE" = "red", "FALSE" = "black")) +
  theme(legend.position = "none")

or_plot

#ggsave("/wynton/group/andrews/users/achatterjee/mtdnacn/Brian-Estimating-Causality-mtDNAcn-on-Alzheimer/results/Aadrita_results/plots/OR_lhc-mr_reverse_dir.png", or_plot, units = "in", width = 5, height = 4, dpi = 300) 
```

